extend type Query {
  activityLogsList(filter: FilterActivityLogs, pagination: PaginationInput): ActivityLogsList
  activityLogsNews(pagination: PaginationInput, id: Int): ActivityLogsNewsList
  activityLogsOptions: [ActivityLogsOptions]
}

input FilterActivityLogs {
  type: String
}

type ActivityLogsOptions {
  type: String
}

type ActivityLogsNewsList {
  data: [ActivityLogsNews]
  pagination: Pagination
}

type ActivityLogsNews {
  id: Int
  type: String
  user_id: Int
  activity: JSON
  user: User
}

type ActivityLogsList {
  data: [ActivityLogs]
  pagination: Pagination
}

type ActivityLogs {
  id: Int
  type: String
  user_id: Int
  activity: JSON
  user: User
}
