extend type Query {
  activityLogsList(filter: FilterActivityLogs, pagination: PaginationInput): ActivityLogsList @auth(public: true)
  activityLogsNews(pagination: PaginationInput, id: Int): ActivityLogsNewsList @auth(public: true)
  activityLogsOptions: [ActivityLogsOptions] @auth(public: true)
}

input FilterActivityLogs {
  type: String
}

type ActivityLogsOptions {
  type: String
}

type ActivityLogsNewsList {
  data: [ActivityLogsNews]
  pagination: Pagination
}

type ActivityLogsNews {
  id: Int
  type: String
  user_id: Int
  activity: JSON
  user: User
}

type ActivityLogsList {
  data: [ActivityLogs]
  pagination: Pagination
}

type ActivityLogs {
  id: Int
  type: String
  user_id: Int
  activity: JSON
  user: User
}
