extend type Query {
  me: Me
  adminMe(websiteId: Int, clientToken: String): Me
}

extend type Mutation {
  signIn(input: SignInInput): Token
  signOut(token: String!): Boolean
  signInSuperAdmin(input: SignInInput): Token
  signOutSuperAdmin(token: String!): Boolean
  changePassword(password: String!): Boolean
}

input SignInInput {
  username: String!
  password: String!
}

type Token {
  token: String
}

type Me {
  id: Int
  username: String
  fullname: String
  profilePicture: String
  roleName: String
  contact_district: String
  contact_commune: String
  contact_city_or_province: String
  contact_village: String
  phoneNumber: String
  email: String
  roleId: Int
}
