extend type Query {
  countryList(websiteId: Int!, pagination: PaginationInput): CountryList
  countryDetail(websiteId: Int!, countryId: Int!): Country
}

extend type Mutation {
  updateCountry(countryId: Int!, websiteId: Int!, input: CountryInput): Boolean
}

type CountryList {
  data: [Country]
  pagination: Pagination
}

type CountryName {
  kh: String
  en: String
}

type Country {
  id: Int
  countryName: CountryName
  code: String
  country_image: String
}

input CountryInput {
  country_name_en: String
  country_name_kh: String
  code: String
  country_image: String
}
