extend type Query {
  documentCategoryList(pagination: PaginationInput, filter: FilterDocumentCategory): DocumentCategoryList
  documentCategoryDetail(id: Int!): DocumentCategory
  publicDocumentCategoryList(pagination: PaginationInput, filter: FilterDocumentCategory): JSON
}

extend type Mutation {
  createDocumentCategory(input: DocumentCategoryInput): Int!
  updateDocumentCategory(id: Int!, input: DocumentCategoryInput): Boolean
}

type DocumentCategory {
  id: Int
  category_name: String
}

type DocumentCategoryList {
  data: [DocumentCategory]
  pagination: Pagination
}

input DocumentCategoryInput {
  category_name: String
  parent_id: Int
}

input FilterDocumentCategory {
  category_name: String
  branch_level: Int
  brand_id: Int
}

enum Status {
  ALL
  PARENT
}
