scalar JSON
scalar JSONObject
scalar Upload

directive @auth(roles: [String], public: Boolean) on FIELD_DEFINITION

type Query {
  testing: String @auth(public: true)
}

type Mutation {
  testing: Boolean @auth(public: true)
}

type Subscription {
  testing: String
}

input PaginationInput {
  page: Int
  size: Int
}

type Pagination {
  total: Int
  size: Int
  current: Int
}
