extend type Query {
  hrDepartmentList(branch_level: Int, parent_id: Int): JSON
  hrDepartment(id: Int!): HrDepartment
  hrDepartmentUsersCount(pagination: PaginationInput, filter: HrDepartmentUsersCountFilter): JSON
}

extend type Mutation {
  createHrDepartment(input: HrDepartmentInput): Int
  updateHrDepartment(id: Int!, input: HrDepartmentInput): Boolean
  removeHrDepartment(id: Int!): Boolean
}

input HrDepartmentUsersCountFilter {
  parent_id: Int
  type: HrDepartmentUsersCountEnum
  officerName: String
}

enum HrDepartmentUsersCountEnum {
  DEPARTMENT
  OFFICE
  GENERAL_DEPARTMENT
}

type HrDepartmentList {
  data: [HrDepartment]
}

type HrDepartment {
  id: Int
  name: String
  parent_id: Int
}

input HrDepartmentInput {
  name: String
  parent_id: Int
}
