extend type Query {
  importsList: ImportsList
  importsDetail(id: Int!): Imports
}

extend type Mutation {
  createImports(input: ImportsInput): Int!
  updateImports(id: Int!, input: ImportsInput): Boolean
}

type ImportsList {
  data: [Imports]
}

type Imports {
  id: Int
  name: String
}

input ImportsInput {
  name: String
  data: [ImportsInputDetail]
}

input ImportsInputDetail {
  year: String
  month: String
  origin_country: String
  hs_code: String
  net_weight_kgm: String
  supplementary_unit: String
  quantity: String
  custom_value_khr: Float
  custom_value_usd: Float
}
