extend type Query {
  importExportReport(filter: ImportExportFilter): JSON
  importExportTopTenCountryVolume: ImportExportTopTenCountryVolumeList
}

input ImportExportFilter {
  countries: [String]
  timeframe: String
  year: String
  second_year: String
  month: String
  second_month: String
  semester: String
  trimester: String
}

type ImportExportTopTenCountryVolumeList {
  data: ImportExportTopTenCountryVolume
}

type ImportExportTopTenCountryVolume {
  imports: [ImportExportTopTenCountryVolumeItem]
  exports: [ImportExportTopTenCountryVolumeItem]
  volumes: [ImportExportTopTenCountryVolumeItem]
}

type ImportExportTopTenCountryVolumeItem {
  country: String
  country_name: String
  volume: String
  country_image: String
}
