extend type Query {
  mediaList(websiteId: Int!, pagination: PaginationInput): MediaList
}

extend type Mutation {
  createMedia(websiteId: Int!, input: MediaInput): Int!
  removeMedia(websiteId: Int!, mediaId: Int!, thumbnail: String!): Boolean
}

type Media {
  id: Int
  image_url: String
}

type MediaList {
  data: [Media]
  pagination: Pagination
}

input MediaInput {
  image_url: String
}
