extend type Query {
  newsCategoryList(websiteId: Int!, pagination: PaginationInput): NewsCategoryList
  newsCategoryDetail(websiteId: Int!, id: Int!): NewsCategory
  publicNewsCategoryList: [NewsCategory]
  publicNewsCategoryDetail(id: Int!): NewsCategory
}

extend type Mutation {
  createNewsCategory(websiteId: Int!, input: NewsCategoryInput): Int!
  updateNewsCategory(websiteId: Int!, id: Int!, input: NewsCategoryInput): Boolean
}

type NewsCategoryList {
  data: [NewsCategory]
  pagination: Pagination
}

type NewsCategory {
  id: Int
  name: String
  created_at: String
  news: [News]
}

input NewsCategoryInput {
  name: String
}
