extend type Query {
  notifications: [Notification]
}

extend type Mutation {
  pushNotification(name: String!, websiteId: Int!): Notification
}

extend type Subscription {
  newNotification: Notification
}

type Notification {
  name: String
}
