extend type Query {
  orderList(status: [OrderStatus], orderCode: String): JSON @auth(public: true)
}

extend type Mutation {
  createOrder(data: [OrderCartInput], customerId: Int, address: String): Boolean @auth(public: true)
  changeOrderStatus(status: OrderStatus!, orderItemId: Int!, note: String): Boolean @auth(public: true)
}

input OrderCartInput {
  productId: Int
  skuId: Int
  price: Float
  discountPrice: Float
  qty: Int
}

enum OrderStatus {
  ORDER_RECEIVED
  ORDER_PROCESSING
  READY_TO_DELIVERY
  ORDER_DELIVERY
  CONFIRM_PICK_UP
  RETURN
}
