extend type Query {
  playgroundList: PlaygroundList @auth(public: true)
}

extend type Mutation {
  createPlayground(input: PlaygroundInput): Int! @auth(public: true)
}

type Playground {
  id: Int
  title: String
}

type PlaygroundList {
  data: [Playground]
}

input PlaygroundInput {
  title: String
}
