extend type Query {
  pluginList: PluginList
  plugin(id: Int): Plugin
}

extend type Mutation {
  createPlugin(input: PluginInput): Int
  updatePlugin(id: Int, input: PluginInput): Boolean
}

type PluginList {
  data: [Plugin]
}

type Plugin {
  id: Int
  name: String
  website_id: Int
  access: Access
}

type Access {
  read: Boolean
  create: Boolean
  edit: Boolean
  remove: Boolean
}

input PluginInput {
  name: String
  website_id: Int
}
