extend type Query {
  employeeReport(pagination: PaginationInput, filter: EmployeeReportFilter): EmployeeReportList
}

type EmployeeReportList {
  data: [HrEmployee]
  pagination: Pagination
}

input EmployeeReportFilter {
  all: String
  officerName: String
  generalDepartmentId: Int
  departmentId: Int
  officeId: Int
}
