extend type Query {
  roleList: RoleList @auth(public: true)
  role(id: Int): Role @auth(public: true)
  adminRoleList: RoleList @auth(public: true)
  hasRole(userId: Int!): Role @auth(public: true)
  adminHasRole(userId: Int!): Role @auth(public: true)
  roleDetail(roleId: Int!): Role @auth(public: true)
}

extend type Mutation {
  createRole(input: RoleInput, permission: RolePermissionInput): Int @auth(public: true)
  updateRole(id: Int, input: RoleInput): Boolean @auth(public: true)
  roleManageAccess(roleId: Int!, input: RoleAccessInput): Boolean @auth(public: true)
  adminAssignRoleToUser(userId: Int!, roleId: Int!): Boolean @auth(public: true)
  setRoleToUser(userId: Int!, roleId: Int!): Boolean @auth(public: true)
}

type RoleList {
  data: [Role]
  permission: RolePermission
}

type Role {
  id: Int
  name: String
  access: RoleAccess
}

input RoleAccessInput {
  read: Boolean
  write: Boolean
  modify: Boolean
  remove: Boolean
  generalDepartmentRead: Boolean
  generalDepartmentWrite: Boolean
  generalDepartmentModify: Boolean
  generalDepartmentRemove: Boolean
  departmentRead: Boolean
  departmentWrite: Boolean
  departmentModify: Boolean
  departmentRemove: Boolean
  officeRead: Boolean
  officeWrite: Boolean
  officeModify: Boolean
  officeRemove: Boolean
  officerRead: Boolean
  officerWrite: Boolean
  officerModify: Boolean
  officerRemove: Boolean
}

type RoleAccess {
  read: Boolean
  write: Boolean
  modify: Boolean
  delete: Boolean
  generalDepartmentRead: Boolean
  generalDepartmentWrite: Boolean
  generalDepartmentModify: Boolean
  generalDepartmentRemove: Boolean
  departmentRead: Boolean
  departmentWrite: Boolean
  departmentModify: Boolean
  departmentRemove: Boolean
  officeRead: Boolean
  officeWrite: Boolean
  officeModify: Boolean
  officeRemove: Boolean
  officerRead: Boolean
  officerWrite: Boolean
  officerModify: Boolean
  officerRemove: Boolean
}

input RoleInput {
  name: String
}

type RolePermission {
  isCreated: Boolean
  isModified: Boolean
  isRemove: Boolean
  isList: Boolean
  isDetail: Boolean
}

input RolePermissionInput {
  isCreated: Boolean
  isModified: Boolean
  isRemove: Boolean
  isList: Boolean
  isDetail: Boolean
}
