extend type Query {
  roleList(websiteId: Int!): RoleList
  role(id: Int): Role
  adminRoleList(websiteId: Int!): RoleList
  hasRole(userId: Int!, websiteId: Int!): Role
  adminHasRole(userId: Int!, websiteId: Int!): Role
  roleDetail(websiteId: Int!, roleId: Int!): Role
}

extend type Mutation {
  createRole(input: RoleInput, permission: RolePermissionInput): Int
  updateRole(id: Int, input: RoleInput): Boolean
  roleManageAccess(websiteId: Int!, roleId: Int!, read: Boolean, write: Boolean, modified: Boolean): Boolean
}

type RoleList {
  data: [Role]
  permission: RolePermission
}

type Role {
  id: Int
  name: String
  website_id: Int
  access: Access
}

input RoleInput {
  name: String
  website_id: Int
}

type RolePermission {
  isCreated: Boolean
  isModified: Boolean
  isRemove: Boolean
  isList: Boolean
  isDetail: Boolean
}

input RolePermissionInput {
  isCreated: Boolean
  isModified: Boolean
  isRemove: Boolean
  isList: Boolean
  isDetail: Boolean
}
