extend type Query {
  superAdminList: SuperAdminList
  superAdmin(id: Int): SuperAdminList
}

extend type Mutation {
  createSuperAdmin(input: SuperAdminInput): Int
  updateSuperAdmin(id: Int, input: SuperAdminInput): Boolean
}

type SuperAdminList {
  data: [SuperAdmin]
}

type SuperAdmin {
  id: Int
  username: String
  fullname: String
}

input SuperAdminInput {
  username: String
  password: String
  fullname: String
}
