extend type Mutation {
  singleUpload(file: Upload!): UploadedFile @auth(public: true)
  upload(attachment: [Upload!]): [Attachment!]! @auth(public: true)
}

type UploadedFile {
  filename: String!
  url: String!
  fileSize: String!
  mimetype: String!
  width: String!
  height: String!
}
