extend type Query {
  adminUserList: UserList
  adminUserDetail(id: Int!): User
  userList: UserList
  userDetail(id: Int!): User
}

extend type Mutation {
  adminCreateUser(input: UserInput): Int!
  adminUpdateUser(id: Int!, input: UserInput): Boolean
  createUser(input: UserInput): Int!
  updateUser(id: Int!, input: UserInput): Boolean
}

type User {
  id: Int
  fullname: String
  username: String
}

type UserList {
  data: [User]
}

input UserInput {
  fullname: String
  username: String
  password: String
  contact_village: String
  contact_district: String
  contact_kanh: String
  contact_city_or_province: Int
  district: String
  commune: String
  province_id: Int
  village_or_group: String
}
