extend type Query {
  userList: UserList
  userDetail(id: Int!): User
}

extend type Mutation {
  createUser(input: UserInput): Int!
  updateUser(id: Int!, input: UserInput): Boolean
}

type User {
  id: Int
  fullname: String
  username: String
}

type UserList {
  data: [User]
}

input UserInput {
  fullname: String
  username: String
  password: String
}
