extend type Query {
  adminUserList(pagination: PaginationInput): UserList
  adminUserDetail(id: Int!): User
  userList: UserList
  userDetail(id: Int!): User
}

extend type Mutation {
  adminCreateUser(input: UserInput): Int!
  adminUpdateUser(id: Int!, input: UserInput): Boolean
  createUser(input: UserInput): Int!
  updateUser(id: Int!, input: UserInput): Boolean
}

type User {
  id: Int
  fullname: String
  username: String
  email: String
  phoneNumber: String
  profile_picture: String
}

type UserList {
  data: [User]
  pagination: Pagination
}

input UserInput {
  fullname: String
  username: String
  password: String
  email: String
  phoneNumber: String
  profile_picture: String
}

enum UserGender {
  MALE
  FEMALE
}
