extend type Query {
  websiteList: WebsiteList
  website(id: Int): Website
}

extend type Mutation {
  createWebsite(input: WebsiteInput): Int
  updateWebsite(id: Int, input: WebsiteInput): Boolean
  addPeopleToWebsite(websiteId: Int!, input: [UserInputId]): Boolean
  addPluginToWebsite(websiteId: Int!, input: [PluginInputId]): Boolean
}

type WebsiteList {
  data: [Website]
}

type Website {
  name: String
  description: String
}

input WebsiteInput {
  name: String
  description: String
}

input UserInputId {
  userId: Int
}

input PluginInputId {
  pluginId: Int
}
